### ISSUE TITLE
Псевдо-кнопка должна быть видна на тёмном фоне

### ISSUE THREAD

**Issue by arteg** [yandex-ui/stylobate-islands#58]
Нужен параметр для скина псевдо-кнопки, например, `invert`.
У меня не вышло это реализовать, т.к. не понял, как прокинуть параметр в `skin-islands-pseudo-button_hover`.

**Comment by kizu** [comment]
- stylobate-islands@0.24.0

http://yandex-ui.github.io/stylobate-islands/skins/#skin-islands-pseudo-button
