### ISSUE TITLE
Дробный box-shadow у промо-кнопки вычисляется по-разному

### ISSUE THREAD

**Issue by arteg** [yandex-ui/stylobate-islands#65]
У промо-кнопки в размере xl, box-shadow у :before задан [**-0.085em**](https://github.com/yandex-ui/stylobate-islands/blob/master/lib/skins/promo-button/skin-islands-promo-button.styl#L74) при размере шрифта **36px**. Итоговое значение **-3.06px** округляется до **-3px** в Я.Бро 14.2, но до **-4px** в FF28 и Chrome Canary (36.0.1917.0).

Дизайнеры замечают разницу, говоря, что текст внутри кнопки не отцентрирован по вертикали.

Либо забиваем, либо выставляем целые box-shadow для каждого размера...

**Comment by kizu** [comment]
Поправил, сделал как в макетах — для обычной и маленькой жёстко 1 пиксель, для большой — два, для очень большой — три.

**Comment by arteg** [comment]
:+1:
