### ISSUE TITLE
Выравнивание текста и хинта в инпутах по центру

### ISSUE THREAD

**Issue by arteg** [yandex-ui/stylobate-islands#66]
Дизайнеры хотят.

**Comment by kizu** [comment]
По горизонтали? Можно чуть поподробнее? :)

**Comment by arteg** [comment]
Да, по горизонтали, как на текущем хост-руте.

**Comment by kizu** [comment]
Добавил параметр `centered`, но он будет работать только для простых инпутов. Для обычных сложных инпутов нужно будет вручную text-align: center пока прописывать, потом как-нибудь я всё равно собираюсь сделать нормальный скин для них, так как сейчас там многовато всякого и так приходится им прописывать вне стилобата.
