### ISSUE TITLE
Required $this

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/stylobate-islands#78]
I want to do a simple thing:

```
.my-selector
  skin-islands-action-button_hover()

.my-another-selector
  skin-islands-button_pressed()
```

It used to work like a charm. Now stylus says that `$this` argument is required.
I can do something like this to hack:

```
skin-islands-action-button_hover({
    params: {},
    selectors: {}
})
```

but I don't understand why I should to. How I can handle it properly?

**Comment by kizu** [comment]
The inner API of kinds and skins was changed, if you'd like to call some skin or kind, you have two options:
1. For skins you can use `global_skin`: `global_skin: islands-action-button_hover`.
2. You can also use built-in function `stylobate_this()`: `skin-islands-action-button_hover(stylobate_ths())` which would put the proper empty `$this`.
